name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 22 8 *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v4.1.7
      - name: Setup NodeJs
        uses: actions/setup-node@v4.0.3
        with:
          check-latest: true
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v4.0.2
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
      - name: Commit and Push new README.md to the repository
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: main
